@OrderFactory.ImmutableLedger.FakesGeneratorApi_HostAddress = http://localhost:5246

POST {{OrderFactory.ImmutableLedger.FakesGeneratorApi_HostAddress}}/api/CustomerGenerator/
Accept: application/json

###